import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import ReactQueryProvider from "./ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <div className="relative min-h-screen bg-background text-foreground artistic-bg">
          <div className="pointer-events-none fixed inset-0 -z-10 artistic-overlay">
            <div className="absolute inset-0 pattern-grid opacity-15" />
            <div className="absolute inset-0 pattern-dots opacity-10" />
          </div>

          <ReactQueryProvider>
            <TooltipProvider>
              <AuthProvider>
                <Toaster />
                {children}
              </AuthProvider>
            </TooltipProvider>
          </ReactQueryProvider>
        {/* </div> */}
      </body>
    </html>
  );
}
